
  <?php  
        $orders = $params['orders'];
        $orderStatuses = SystemOptions::getOrderStatuses();
        $classColors = array(
            '0' => 'danger',
            '1' => 'info',
            '2' => 'info',
            '3' => 'warning',
            '4' => 'success',
        );
  ?>

<div class="table-responsive">
    <table class="table table-hover table-condensed">
      <thead>
        <tr>
          <th>Customer</th>
          <th>CID</th>
          <th>OID</th>
          <th>Pickup Time</th>
          <th>Address</th>
          <th>Dropoff Time</th>
          <th>Special Instructions</th>
          <th>Status</th>
          <th>Actions</th>
        </tr>
      </thead>
      <tbody>
      <?php foreach($orders as $order): ?>    
        <tr class="<?php echo ($classColors[$order['status']]) ? $classColors[$order['status']] : ' '; ?>">
          <td><?php echo $order['first_name'].' '.$order['last_name']; ?></td>
          <td><?php echo $order['users_id']; ?></td>
          <td><?php echo $order['id']; ?></td>
          <td><?php echo date('d M Y, g:i a', strtotime($order['pickup_time'])); ?></td>
          <td><?php echo $order['address']; ?></td>
          <td><?php echo date('d M Y', strtotime($order['dropoff_time'])); ?> 6pm-9pm</td>
          <td><?php echo $order['special_instructions']; ?></td>
          <td><?php echo ( $orderStatuses[$order['status']] ) ? $orderStatuses[$order['status']] : ' - '; ?></td>
          <td>
              <a href="<?php echo Utility::base_url(); ?>/orders/edit?oid=<?=$order['id'];?>" title="Edit"><span class="glyphicon glyphicon-pencil"></span></a>
              <a href="<?php echo Utility::base_url(); ?>/orders/items/add?oid=<?=$order['id'];?>" title="Add Items"><span class="glyphicon glyphicon-plus"></span></a>
              <a href="" title="Delete Order" onclick="deleteOrder('<?=$order['id'];?>')"><span class="glyphicon glyphicon-remove"></span></a>
          </td>
        </tr>
      <?php endforeach; ?>  
      </tbody>
    </table>
</div>
<script type="text/javascript">
    function deleteOrder(orderId){
        event.preventDefault();
        
        var url = "<?php echo Utility::base_url(); ?>/orders/delete";
        if(confirm("Are you sure you want to delete this record?")){
            $.ajax({
                type        : 'POST', // define the type of HTTP verb we want to use (POST for our form)
                url         : url, // the url where we want to POST
                data        : {'oid' : orderId}, // our data object
                dataType    : 'json', // what type of data do we expect back from the server
                encode          : true
            })
                // using the done promise callback
                .done(function(data) {
                    if(data.success){ console.log("here");
                        location.reload();
                    }else if(data.error){
                        alert(data.error);
                    }
                    // log data to the console so we can see
                    console.log(data); 
                    // here we will handle errors and validation messages
                });
        }
    }
</script>