
  <?php  
        $users = $params['users'];
        
  ?>
<div class="table-responsive">
    <table class="table table-hover table-condensed">
      <thead>
        <tr>
          <th>Name</th>
          <th>Address</th>
          <th>Date Created</th>
          <th>Email</th>
          <th>Phone</th>
          <!-- th>Actions</th -->
        </tr>
      </thead>
      <tbody>
      <?php foreach($users as $user): ?>
        <tr class="">
          <td><?php echo $user['first_name'].' '.$user['last_name']; ?></td>
          <td><?php echo $user['address']; ?></td>
          <td><?php echo date('d M Y, g a', strtotime($user['date_created'])); ?></td>
          <td><?php echo $user['email']; ?></td>
          <td><?php echo $user['phone']; ?></td>
          <!-- td>
              <a href="" title="Edit"><span class="glyphicon glyphicon-pencil"></span></a>
              <a href="" title="Add Items"><span class="glyphicon glyphicon-plus"></span></a>
          </td -->
        </tr>
        
      <?php endforeach; ?>  
      </tbody>
    </table>
</div>
