

<style>
    body{
        width: 100%;
        height: 100%;
        font-family: 'Open Sans', sans-serif;
        background-color: #092756;
    }
    input {
        width: 100%;
        margin-bottom: 10px;
        background: rgba(0,0,0,0.3);
        border: none;
        outline: none;
        padding: 10px;
        font-size: 13px;
        color: #fff;
        text-shadow: 1px 1px 1px rgba(0,0,0,0.3);
        border: 1px solid rgba(0,0,0,0.3);
        border-radius: 4px;
        box-shadow: inset 0 -5px 45px rgba(100,100,100,0.2), 0 1px 1px rgba(255,255,255,0.2);
        -webkit-transition: box-shadow .5s ease;
        -moz-transition: box-shadow .5s ease;
        -o-transition: box-shadow .5s ease;
        -ms-transition: box-shadow .5s ease;
        transition: box-shadow .5s ease;
    }
    .login {
    position: absolute;
    top: 30%;
    left: 50%;
    margin: -150px 0 0 -150px;
    width: 300px;
    height: 300px;
}
.login h1 {
    color: #fff;
    text-shadow: 0 0 10px rgba(0,0,0,0.3);
    letter-spacing: 1px;
    text-align: center;
}
.lead{
    text-align: center;
}
.msg{
    color: #FFF;
}
</style> 
<div class="login">
	<h1>Login</h1>
        <p class="lead"><img width="100" src="<?php echo Utility::theme_url(); ?>images/logo.png" ></p>
    <form method="post" action="<?php echo Utility::base_url(); ?>/admin/login">
    	<input type="text" name="u" placeholder="Username" required="required" />
        <input type="password" name="p" placeholder="Password" required="required" />
        <button type="submit" class="btn btn-primary btn-block btn-large">Let me in.</button>
    </form>
        <p class="msg"><?php echo (isset($params['error'])) ? $params['error'] : '' ?></p>
        <p class="msg"><?php echo (isset($params['msg'])) ? $params['msg'] : '' ?></p>
</div>