<div class="row">
    
    <div class="col-md-3">
        <div class="panel panel-primary"> 
            <div class="panel-heading"> 
                <h3 class="panel-title">Area Report</h3> 
            </div> 
            <div class="panel-body"> <a href="<?php echo Utility::base_url(); ?>/reports/area_report" >Monthly area specific report </a></div> 
        </div>
    </div>
    <div class="col-md-3">
        <div class="panel panel-primary"> 
            <div class="panel-heading"> 
                <h3 class="panel-title">Sales Report</h3> 
            </div> 
            <div class="panel-body"> <a href="<?php echo Utility::base_url(); ?>/reports/sales_report" >Monthly sales report </a></div> 
        </div>
    </div>
    
    <div class="col-md-3">
        <div class="panel panel-primary"> 
            <div class="panel-heading"> 
                <h3 class="panel-title">Selling Report</h3> 
            </div> 
            <div class="panel-body"> Most selling report </div> 
        </div>
    </div>
    <div class="col-md-3">
        <div class="panel panel-primary"> 
            <div class="panel-heading"> 
                <h3 class="panel-title">Orders Report</h3> 
            </div> 
            <div class="panel-body"> Number of Canceled / Completed Orders  </div> 
        </div>
    </div>
    <div class="col-md-3">
        <div class="panel panel-primary"> 
            <div class="panel-heading"> 
                <h3 class="panel-title">Customer Report</h3> 
            </div> 
            <div class="panel-body"> Most repetitive customer </div> 
        </div>
    </div>
    
    <div class="col-md-3">
        <div class="panel panel-primary"> 
            <div class="panel-heading"> 
                <h3 class="panel-title">Revenue Report</h3> 
            </div> 
            <div class="panel-body"> Total revenue in a month </div> 
        </div>
    </div>
    
    <div class="col-md-3">
        <div class="panel panel-primary"> 
            <div class="panel-heading"> 
                <h3 class="panel-title">Registrations Report</h3> 
            </div> 
            <div class="panel-body">Monthly registrations and their details </div> 
        </div>
    </div>
    <div class="col-md-3">
        <div class="panel panel-primary"> 
            <div class="panel-heading"> 
                <h3 class="panel-title">Garments Cleaning Report</h3> 
            </div> 
            <div class="panel-body"> Total number of garments completed in a month </div> 
        </div>
    </div>
    <div class="col-md-3">
        <div class="panel panel-primary"> 
            <div class="panel-heading"> 
                <h3 class="panel-title">Non-Ordered Customers Report</h3> 
            </div> 
            <div class="panel-body"> People who signed in but didn't order </div> 
        </div>
    </div>
</div>
